### ISSUE TITLE
Error when copying build in Dockerfile in 'Publish Docker Image' action

### ISSUE THREAD

**Issue by AristideBH** [khromov/self-hosted-sveltekit-demo#6]
Hi Stanislas,
To extend on the reported error I got, here is the full detail.
During the copy of the build folder in the Docker Image, I get the following error : 
```
#14 [stage-1 5/7] COPY --from=sk-build /usr/src/app/package.json /usr/src/app/package.json
#14 CANCELED
#15 [stage-1 6/7] COPY --from=sk-build /usr/src/app/package-lock.json /usr/src/app/package-lock.json
#15 CACHED
#16 [stage-1 7/7] COPY --from=sk-build /usr/src/app/build /usr/src/app/build
#16 ERROR: failed to calculate checksum of ref 6[252](https://github.com/AristideBH/aristide-bh/actions/runs/7928348051/job/21646423378#step:5:253)96d6-9be1-4356-a58b-91c3a8df5f0b::jbf059lhqsci6mtff1l8sm5a7: "/usr/src/app/build": not found
------
 > [stage-1 7/7] COPY --from=sk-build /usr/src/app/build /usr/src/app/build:
------
Dockerfile:23
--------------------
  21 |     COPY --from=sk-build /usr/src/app/package.json /usr/src/app/package.json
  22 |     COPY --from=sk-build /usr/src/app/package-lock.json /usr/src/app/package-lock.json
  23 | >>> COPY --from=sk-build /usr/src/app/build /usr/src/app/build
  24 |     
  25 |     EXPOSE 3000
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 625296d6-9be1-4356-a58b-91c3a8df5f0b::jbf059lhqsci6mtff1l8sm5a7: "/usr/src/app/build": not found
Error: The process '/usr/bin/docker' failed with exit code 1
```

I updated my Dockerfile with node 21-alpine to support Sharp Image package, and added the ARG for env variables support.

```Dockerfile
FROM node:21-alpine AS sk-build
WORKDIR /usr/src/app

ARG TZ=Europe/Paris
ARG PUBLIC_DIRECTUS_URL
ARG PUBLIC_COOKIE_DOMAIN

COPY . /usr/src/app
RUN apk --no-cache add curl tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN npm install --force
RUN npm run build

FROM node:21-alpine
WORKDIR /usr/src/app

ARG TZ=Europe/Paris
RUN apk --no-cache add curl tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=sk-build /usr/src/app/package.json /usr/src/app/package.json
COPY --from=sk-build /usr/src/app/package-lock.json /usr/src/app/package-lock.json
COPY --from=sk-build /usr/src/app/build /usr/src/app/build

EXPOSE 3000
CMD ["node", "build/index.js"]
```

I also updated the action yml to reflect that change : 
```yml
...
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          buildArgs: |
            PUBLIC_DIRECTUS_URL="https://admin.aristide-bh.com"
            PUBLIC_COOKIE_DOMAIN="aristide-bh.com"
          containerRegistry: true
...
```
I also added the files to  `.dockerignore` as per your repo demo.
I add everything building correctly four months ago before I really dive into the the local frontend development, but I'm kinda crawling with errors now :/

Thanks again for your time 🙏
